# Dracula Tmux Theme

set -g default-terminal "screen-256color"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

# Dracula configuration
set -g @dracula-show-left-icon session

# Start window and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse support
set -g mouse on

# Change prefix to CTRL+A
set -g prefix C-a
unbind C-b
bind C-a send-prefix
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Reload config
bind r source-file ~/.tmux.conf

# Initialize TPM (keep this at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
