services:
  pg15:
    image: postgres:15
    # ports:
    #   - "5433:5432"
    # network_mode: "host"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg15_data:/var/lib/postgresql/data

  pg18:
    image: postgres:18
    # ports:
      # - "5432:5432"
    environment:
      - POSTGRES_DB=monoline_webapp_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg18_data:/var/lib/postgresql

  redis:
    image: redis:7
    # network_mode: "host"
    ports:
      - "6379:6379"

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
  #     PGADMIN_DEFAULT_PASSWORD: postgres

volumes:
  pg15_data:
  pg18_data:

