FROM ruby:3.4.2

RUN mkdir -p /monoline
WORKDIR /monoline

RUN apt update
RUN apt install -y apt-transport-https

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -

RUN apt update \
  && apt install -y \
    build-essential \
    tzdata \
    nodejs \
    npm \
    yarn \
    postgresql-client \
    zsh \
    neovim \
    btop \
    iputils-ping

# ENV RAILS_SERVE_STATIC_FILES true
ENV RAILS_LOG_TO_STDOUT true

COPY ../Gemfile Gemfile.lock /monoline/

RUN gem install bundler -v 2.2.20
RUN bundle install

# Git configuration
RUN git config --global --add safe.directory /monoline
RUN git config --global --add safe.directory /workspaces/web-app

# Oh-My-Zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
RUN sed -i "s/plugins=(git)/plugins=(git zsh-autosuggestions)/" ~/.zshrc

# Graphite
RUN npm install -g @withgraphite/graphite-cli@stable

RUN gem install yard

# COPY . /usr/src/app
# RUN chmod +x entrypoint.sh entrypoint_worker.sh

# ENTRYPOINT [ "bash", "entrypoint.sh" ]
# To run Sidekiq as a worker overwrite the CMD command to `bundle exec sidekiq` on Render
