---
- hosts: localhost
  become: yes  # Para rodar comandos como sudo
  tasks:
    - name: Atualizar lista de pacotes
      apt:
        update_cache: yes

    - name: Garantir que os pacotes necessários estão instalados
      apt:
        name:
          - age
          - ansible-core
          - bat
          - btop
          - build-essential
          - curl
          - gcc
          - git
          - neofetch
          - neovim
          - procps
          - ripgrep
          - tldr
          - tmux
          - unzip
          - wget
          - zoxide
          - zsh
        state: latest
